-- ============================================
-- FUNDIFY Database Setup
-- STEP 1: Run this file in MySQL Workbench
-- STEP 2: Run "node setup.js" in terminal
-- ============================================

CREATE DATABASE IF NOT EXISTS fundify;
USE fundify;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS fraud_logs;
DROP TABLE IF EXISTS campaign_updates;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS donations;
DROP TABLE IF EXISTS campaigns;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('donor','fundraiser','admin') DEFAULT 'donor',
    is_verified TINYINT(1) DEFAULT 0,
    is_banned TINYINT(1) DEFAULT 0,
    otp_code VARCHAR(6) DEFAULT NULL,
    otp_expires DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE campaigns (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    goal_amount DECIMAL(12,2) NOT NULL,
    raised_amount DECIMAL(12,2) DEFAULT 0.00,
    deadline DATE NOT NULL,
    category VARCHAR(100) DEFAULT 'General',
    image_url VARCHAR(255) DEFAULT NULL,
    status ENUM('pending','active','rejected','completed','flagged') DEFAULT 'pending',
    rejection_reason TEXT DEFAULT NULL,
    fraud_score INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE donations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    campaign_id INT NOT NULL,
    donor_id INT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    is_anonymous TINYINT(1) DEFAULT 0,
    is_flagged TINYINT(1) DEFAULT 0,
    flag_reason VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
    FOREIGN KEY (donor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    campaign_id INT NOT NULL,
    user_id INT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE campaign_updates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    campaign_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);

CREATE TABLE fraud_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    entity_type ENUM('campaign','donation','user') NOT NULL,
    entity_id INT NOT NULL,
    rule_triggered VARCHAR(255) NOT NULL,
    severity ENUM('low','medium','high') DEFAULT 'low',
    resolved TINYINT(1) DEFAULT 0,
    resolved_by INT DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin account is created by running: node setup.js
-- Do NOT add admin here — the password hash must be generated by Node.js
SELECT 'Database created successfully! Now run: node setup.js' as NEXT_STEP;

-- ============================================
-- OTP VERIFICATION COLUMNS
-- Run this if you already have the database set up:
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_code VARCHAR(6) DEFAULT NULL;
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_expires DATETIME DEFAULT NULL;
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified TINYINT(1) DEFAULT 0;
-- ============================================
